### ISSUE TITLE
Make xpcc build with gcc 4.8 from linaro embedded toolchain

### ISSUE THREAD

**Issue by ekiwi** [roboterclubaachen/xpcc#7]
On December 23rd a new linaro embedded toolchain [was released](https://launchpad.net/gcc-arm-embedded/4.8/4.8-2013-q4-major)

Unfortunately our code does not build right out of the box. The first problems I encountered, trying to build for stm32, was in the software spi driver:

```
spi_master.hpp:35:21: error: expected type-specifier before 'GpioUnused'
 typename MISO = GpioUnused
```

a lot of (subsequent??) errors followed.

So I guess this is a thing we should look into.

**Comment by ekiwi** [comment]
Actually avr-g++ seems to have the same issue:

```
> avr-g++ --version
avr-g++ (Fedora 4.8.2-1.fc20) 4.8.2
```

and here the version of my arm-none-eabi-g++

```
> arm-none-eabi-g++ --version
arm-none-eabi-g++ (GNU Tools for ARM Embedded Processors) 4.8.3 20131129 (release) [ARM/embedded-_8-branch revision 205641]
```

**Comment by ekiwi** [comment]
Somehow things seem to fail with an earlier version of g++ as well:

```
> arm-none-eabi-g++ --version
arm-none-eabi-g++ (GNU Tools for ARM Embedded Processors) 4.7.4 20130913 (release) [ARM/embedded-4_7-branch revision 202601]
```

Also it seems to have been broken for some time. Could there be something wrong with my new system?

**Comment by salkinium** [comment]
I had the same problem and "fixed" it, but only in the feature/tolerance branch, which is not merged yet.
See commit f4ee579522ed23ddc8d4eb8c7c233f64034e7ad2.

`#include "../../gpio/software/gpio.hpp"` must be added.
